# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170512_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkbox',
            name='title',
            field=models.CharField(default='fake_title', max_length=50),
            preserve_default=False,
        ),
    ]
